//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NounSharp.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NounSharp.Test.ResponseResource", typeof(ResponseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;collection&quot;: {
        ///    &quot;author&quot;: {
        ///      &quot;location&quot;: &quot;Los Angeles, California, US&quot;,
        ///      &quot;name&quot;: &quot;Iconathon&quot;,
        ///      &quot;permalink&quot;: &quot;/Iconathon1&quot;,
        ///      &quot;username&quot;: &quot;Iconathon1&quot;
        ///    },
        ///    &quot;author_id&quot;: &quot;12701&quot;,
        ///    &quot;date_created&quot;: &quot;2012-01-27 19:15:26&quot;,
        ///    &quot;date_updated&quot;: &quot;2012-12-11 08:40:24&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;icon_count&quot;: &quot;183&quot;,
        ///    &quot;id&quot;: &quot;4&quot;,
        ///    &quot;is_collaborative&quot;: &quot;&quot;,
        ///    &quot;is_featured&quot;: &quot;1&quot;,
        ///    &quot;is_published&quot;: &quot;0&quot;,
        ///    &quot;is_store_item&quot;: &quot;0&quot;,
        ///    &quot;name&quot;: &quot;Iconathon&quot;,
        ///    &quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collection_id {
            get {
                return ResourceManager.GetString("collection_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;generated_at&quot;: &quot;Thu, 05 Mar 2015 20:21:57 GMT&quot;,
        ///  &quot;icons&quot;: [
        ///    {
        ///      &quot;attribution&quot;: &quot;fun by XOXO from The Noun Project&quot;,
        ///      &quot;attribution_preview_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/attribution/23936-600.png&quot;,
        ///      &quot;date_uploaded&quot;: &quot;2013-10-02&quot;,
        ///      &quot;icon_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/svg/7c2f2d9b-068b-484a-9b40-5485d17b6d13.svg?Expires=1425590517&amp;Signature=J7u7PjEV01SnXi3pd3AJCktqoMntim~V1fHQkrFnd~jpZD0kszRivNYabC-6BgQRbjphL9mth1wFngCYYoc5GJth5Ixs1JA4O0TYhyc7yLL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collection_id_icons {
            get {
                return ResourceManager.GetString("collection_id_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;collection&quot;: {
        ///    &quot;author&quot;: {
        ///      &quot;location&quot;: &quot;Los Angeles, US&quot;,
        ///      &quot;name&quot;: &quot;Edward Boatman&quot;,
        ///      &quot;permalink&quot;: &quot;/edward&quot;,
        ///      &quot;username&quot;: &quot;edward&quot;
        ///    },
        ///    &quot;author_id&quot;: &quot;6&quot;,
        ///    &quot;date_created&quot;: &quot;2012-01-27 19:15:26&quot;,
        ///    &quot;date_updated&quot;: &quot;2012-01-27 19:15:26&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;icon_count&quot;: &quot;143&quot;,
        ///    &quot;id&quot;: &quot;2&quot;,
        ///    &quot;is_collaborative&quot;: &quot;&quot;,
        ///    &quot;is_featured&quot;: &quot;1&quot;,
        ///    &quot;is_published&quot;: &quot;1&quot;,
        ///    &quot;is_store_item&quot;: &quot;0&quot;,
        ///    &quot;name&quot;: &quot;National Park Service&quot;,
        ///    &quot;permalin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collection_slug {
            get {
                return ResourceManager.GetString("collection_slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;generated_at&quot;: &quot;Thu, 05 Mar 2015 20:21:57 GMT&quot;,
        ///  &quot;icons&quot;: [
        ///    {
        ///      &quot;attribution&quot;: &quot;Bicycle from The Noun Project&quot;,
        ///      &quot;attribution_preview_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/attribution/79-600.png&quot;,
        ///      &quot;date_uploaded&quot;: &quot;&quot;,
        ///      &quot;icon_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/svg/79_1.svg?Expires=1425590517&amp;Signature=VG4MLr70For8NIW7OaDIXpChNolhZu9ksUWqQUcJocXcowN5g432RnkGl-4CKwwJPUvcg3CvanOhUN49gRd0f8TEFVE7SSQ0zAuUSm-1HUwsYp2SksnqYL9lJzAitq9W3NMd47JlB0W1xBqRQjM~P6p4iUDE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collection_slug_icons {
            get {
                return ResourceManager.GetString("collection_slug_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;collections&quot;: [
        ///    {
        ///      &quot;author&quot;: {
        ///        &quot;location&quot;: &quot;&quot;,
        ///        &quot;name&quot;: &quot;Thomas Jakobsen&quot;,
        ///        &quot;permalink&quot;: &quot;/lewl_roflcopter&quot;,
        ///        &quot;username&quot;: &quot;lewl_roflcopter&quot;
        ///      },
        ///      &quot;author_id&quot;: &quot;695255&quot;,
        ///      &quot;date_created&quot;: &quot;2015-03-05 20:25:58&quot;,
        ///      &quot;date_updated&quot;: &quot;2015-03-05 20:25:58&quot;,
        ///      &quot;description&quot;: &quot;&quot;,
        ///      &quot;id&quot;: &quot;3348&quot;,
        ///      &quot;is_collaborative&quot;: &quot;&quot;,
        ///      &quot;is_featured&quot;: &quot;0&quot;,
        ///      &quot;is_published&quot;: &quot;1&quot;,
        ///      &quot;is_store_item&quot;: &quot;0&quot;,
        ///      &quot;name&quot;: &quot;Dinosaurs&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collections {
            get {
                return ResourceManager.GetString("collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;icon&quot;: {
        ///    &quot;attribution&quot;: &quot;Beauty Salon from The Noun Project&quot;,
        ///    &quot;attribution_preview_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/attribution/15-600.png&quot;,
        ///    &quot;collections&quot;: [
        ///      {
        ///        &quot;author&quot;: {
        ///          &quot;location&quot;: &quot;Los Angeles, US&quot;,
        ///          &quot;name&quot;: &quot;Edward Boatman&quot;,
        ///          &quot;permalink&quot;: &quot;/edward&quot;,
        ///          &quot;username&quot;: &quot;edward&quot;
        ///        },
        ///        &quot;author_id&quot;: &quot;6&quot;,
        ///        &quot;date_created&quot;: &quot;2012-01-27 19:15:26&quot;,
        ///        &quot;date_updated&quot;: &quot;2012-09-27 13:27:02&quot;,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string icon_id {
            get {
                return ResourceManager.GetString("icon_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;icon&quot;: {
        ///    &quot;attribution&quot;: &quot;Globe by Edward Boatman from The Noun Project&quot;,
        ///    &quot;attribution_preview_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/attribution/247-600.png&quot;,
        ///    &quot;collections&quot;: [
        ///      {
        ///        &quot;author&quot;: {
        ///          &quot;location&quot;: &quot;Los Angeles, US&quot;,
        ///          &quot;name&quot;: &quot;Edward Boatman&quot;,
        ///          &quot;permalink&quot;: &quot;/edward&quot;,
        ///          &quot;username&quot;: &quot;edward&quot;
        ///        },
        ///        &quot;author_id&quot;: &quot;6&quot;,
        ///        &quot;date_created&quot;: &quot;2012-01-27 19:15:07&quot;,
        ///        &quot;date_updated&quot;: &quot;2012-10-16 15:37:06&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string icon_term {
            get {
                return ResourceManager.GetString("icon_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;generated_at&quot;: &quot;Thu, 05 Mar 2015 20:21:58 GMT&quot;,
        ///  &quot;icons&quot;: [
        ///    {
        ///      &quot;attribution&quot;: &quot;Fish by Tonielle Krisanski from The Noun Project&quot;,
        ///      &quot;attribution_preview_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/attribution/7770-600.png&quot;,
        ///      &quot;collections&quot;: [],
        ///      &quot;date_uploaded&quot;: &quot;2012-11-15&quot;,
        ///      &quot;icon_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/svg/3377c517-a6a9-477a-a446-cfcba9a4bca1.svg?Expires=1425590518&amp;Signature=OXQLF5~U4AC7pmPnbfgywe4kcjJSGQjQsyHjFqLDF1iAfLDO6nhy~C1h5Gu7-VhI1x9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string icons_term {
            get {
                return ResourceManager.GetString("icons_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;generated_at&quot;: &quot;Thu, 05 Mar 2015 19:51:11 GMT&quot;,
        ///  &quot;recent_uploads&quot;: [
        ///    {
        ///      &quot;attribution&quot;: &quot;jacuzzi by Dream Icons from The Noun Project&quot;,
        ///      &quot;attribution_preview_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/attribution/114404-600.png&quot;,
        ///      &quot;date_uploaded&quot;: &quot;2015-02-27&quot;,
        ///      &quot;icon_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/icon_uploads/d1608409-694f-4f61-843b-28137a650b9c.svg?Expires=1425588671&amp;Signature=j1RpkgmZILLEp9tBSFqjk45LF-0zJDMzT6dT9miF-pJJcN7fgOir8F-u3OPpfMDjP~beV85pp2IYd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recent_uploads {
            get {
                return ResourceManager.GetString("recent_uploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;collection&quot;: {
        ///    &quot;author&quot;: {
        ///      &quot;location&quot;: &quot;US&quot;,
        ///      &quot;name&quot;: &quot;mnmly&quot;,
        ///      &quot;permalink&quot;: &quot;/mnmly&quot;,
        ///      &quot;username&quot;: &quot;mnmly&quot;
        ///    },
        ///    &quot;author_id&quot;: &quot;1&quot;,
        ///    &quot;date_created&quot;: &quot;2012-02-22 13:32:49&quot;,
        ///    &quot;date_updated&quot;: &quot;2012-02-22 13:33:00&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;icon_count&quot;: &quot;3&quot;,
        ///    &quot;id&quot;: &quot;7&quot;,
        ///    &quot;is_collaborative&quot;: &quot;&quot;,
        ///    &quot;is_featured&quot;: &quot;0&quot;,
        ///    &quot;is_published&quot;: &quot;0&quot;,
        ///    &quot;is_store_item&quot;: &quot;1&quot;,
        ///    &quot;name&quot;: &quot;Bicycle&quot;,
        ///    &quot;permalink&quot;: &quot;/mnmly/collection/bicycle&quot;,
        ///    &quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string user_collection_slug {
            get {
                return ResourceManager.GetString("user_collection_slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;collections&quot;: [
        ///    {
        ///      &quot;author&quot;: {
        ///        &quot;location&quot;: &quot;Los Angeles, US&quot;,
        ///        &quot;name&quot;: &quot;Edward Boatman&quot;,
        ///        &quot;permalink&quot;: &quot;/edward&quot;,
        ///        &quot;username&quot;: &quot;edward&quot;
        ///      },
        ///      &quot;author_id&quot;: &quot;6&quot;,
        ///      &quot;date_created&quot;: &quot;2012-08-21 17:39:19&quot;,
        ///      &quot;date_updated&quot;: &quot;2012-08-21 17:40:15&quot;,
        ///      &quot;description&quot;: &quot;&quot;,
        ///      &quot;id&quot;: &quot;15&quot;,
        ///      &quot;is_collaborative&quot;: &quot;&quot;,
        ///      &quot;is_featured&quot;: &quot;1&quot;,
        ///      &quot;is_published&quot;: &quot;1&quot;,
        ///      &quot;is_store_item&quot;: &quot;1&quot;,
        ///      &quot;name&quot;: &quot;Truck&quot;,
        ///      &quot;permali [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string user_collections {
            get {
                return ResourceManager.GetString("user_collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;generated_at&quot;: &quot;Thu, 05 Mar 2015 20:21:59 GMT&quot;,
        ///  &quot;uploads&quot;: [
        ///    {
        ///      &quot;attribution&quot;: &quot;Brazil by Edward Boatman from The Noun Project&quot;,
        ///      &quot;attribution_preview_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/attribution/67379-600.png&quot;,
        ///      &quot;date_uploaded&quot;: &quot;2014-08-28&quot;,
        ///      &quot;icon_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/icon_uploads/51abe2a5-b196-4b9b-97c8-681de2afd3b2.svg?Expires=1425590519&amp;Signature=CDO8gLIDjxy2y~5~CCOsdpvLKl6VTOtwdZafLsy0ectxzbtdg3qnZYKm0UveC1PG3ikrFzMuRrBnyg5tCzS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string user_uploads {
            get {
                return ResourceManager.GetString("user_uploads", resourceCulture);
            }
        }
    }
}
