//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NounSharp.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NounSharp.Test.ResponseResource", typeof(ResponseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;collection&quot;: {
        ///    &quot;author&quot;: {
        ///      &quot;location&quot;: &quot;Los Angeles, California, US&quot;,
        ///      &quot;name&quot;: &quot;Iconathon&quot;,
        ///      &quot;permalink&quot;: &quot;/Iconathon1&quot;,
        ///      &quot;username&quot;: &quot;Iconathon1&quot;
        ///    },
        ///    &quot;author_id&quot;: &quot;12701&quot;,
        ///    &quot;date_created&quot;: &quot;2012-01-27 19:15:26&quot;,
        ///    &quot;date_updated&quot;: &quot;2012-12-11 08:40:24&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;icon_count&quot;: &quot;183&quot;,
        ///    &quot;id&quot;: &quot;4&quot;,
        ///    &quot;is_collaborative&quot;: &quot;&quot;,
        ///    &quot;is_featured&quot;: &quot;1&quot;,
        ///    &quot;is_published&quot;: &quot;0&quot;,
        ///    &quot;is_store_item&quot;: &quot;0&quot;,
        ///    &quot;name&quot;: &quot;Iconathon&quot;,
        ///    &quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collection_id {
            get {
                return ResourceManager.GetString("collection_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;generated_at&quot;: &quot;Thu, 05 Mar 2015 20:21:57 GMT&quot;,
        ///  &quot;icons&quot;: [
        ///    {
        ///      &quot;attribution&quot;: &quot;fun by XOXO from The Noun Project&quot;,
        ///      &quot;attribution_preview_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/attribution/23936-600.png&quot;,
        ///      &quot;date_uploaded&quot;: &quot;2013-10-02&quot;,
        ///      &quot;icon_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/svg/7c2f2d9b-068b-484a-9b40-5485d17b6d13.svg?Expires=1425590517&amp;Signature=J7u7PjEV01SnXi3pd3AJCktqoMntim~V1fHQkrFnd~jpZD0kszRivNYabC-6BgQRbjphL9mth1wFngCYYoc5GJth5Ixs1JA4O0TYhyc7yLL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collection_id_icons {
            get {
                return ResourceManager.GetString("collection_id_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;collection&quot;: {
        ///    &quot;author&quot;: {
        ///      &quot;location&quot;: &quot;Los Angeles, US&quot;,
        ///      &quot;name&quot;: &quot;Edward Boatman&quot;,
        ///      &quot;permalink&quot;: &quot;/edward&quot;,
        ///      &quot;username&quot;: &quot;edward&quot;
        ///    },
        ///    &quot;author_id&quot;: &quot;6&quot;,
        ///    &quot;date_created&quot;: &quot;2012-01-27 19:15:26&quot;,
        ///    &quot;date_updated&quot;: &quot;2012-01-27 19:15:26&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;icon_count&quot;: &quot;143&quot;,
        ///    &quot;id&quot;: &quot;2&quot;,
        ///    &quot;is_collaborative&quot;: &quot;&quot;,
        ///    &quot;is_featured&quot;: &quot;1&quot;,
        ///    &quot;is_published&quot;: &quot;1&quot;,
        ///    &quot;is_store_item&quot;: &quot;0&quot;,
        ///    &quot;name&quot;: &quot;National Park Service&quot;,
        ///    &quot;permalin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collection_slug {
            get {
                return ResourceManager.GetString("collection_slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;generated_at&quot;: &quot;Thu, 05 Mar 2015 20:21:57 GMT&quot;,
        ///  &quot;icons&quot;: [
        ///    {
        ///      &quot;attribution&quot;: &quot;Bicycle from The Noun Project&quot;,
        ///      &quot;attribution_preview_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/attribution/79-600.png&quot;,
        ///      &quot;date_uploaded&quot;: &quot;&quot;,
        ///      &quot;icon_url&quot;: &quot;https://d30y9cdsu7xlg0.cloudfront.net/svg/79_1.svg?Expires=1425590517&amp;Signature=VG4MLr70For8NIW7OaDIXpChNolhZu9ksUWqQUcJocXcowN5g432RnkGl-4CKwwJPUvcg3CvanOhUN49gRd0f8TEFVE7SSQ0zAuUSm-1HUwsYp2SksnqYL9lJzAitq9W3NMd47JlB0W1xBqRQjM~P6p4iUDE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collection_slug_icons {
            get {
                return ResourceManager.GetString("collection_slug_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;collections&quot;: [
        ///    {
        ///      &quot;author&quot;: {
        ///        &quot;location&quot;: &quot;&quot;,
        ///        &quot;name&quot;: &quot;Thomas Jakobsen&quot;,
        ///        &quot;permalink&quot;: &quot;/lewl_roflcopter&quot;,
        ///        &quot;username&quot;: &quot;lewl_roflcopter&quot;
        ///      },
        ///      &quot;author_id&quot;: &quot;695255&quot;,
        ///      &quot;date_created&quot;: &quot;2015-03-05 20:25:58&quot;,
        ///      &quot;date_updated&quot;: &quot;2015-03-05 20:25:58&quot;,
        ///      &quot;description&quot;: &quot;&quot;,
        ///      &quot;id&quot;: &quot;3348&quot;,
        ///      &quot;is_collaborative&quot;: &quot;&quot;,
        ///      &quot;is_featured&quot;: &quot;0&quot;,
        ///      &quot;is_published&quot;: &quot;1&quot;,
        ///      &quot;is_store_item&quot;: &quot;0&quot;,
        ///      &quot;name&quot;: &quot;Dinosaurs&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string collections {
            get {
                return ResourceManager.GetString("collections", resourceCulture);
            }
        }
    }
}
